#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scaffold a new city site from this one.

    python tools/new-city.py

Asks a handful of questions, then creates a sibling folder containing a
complete copy of this project with the CONFIG block, wrangler.toml and web
manifest already rewritten for the new city.

What it copies
    build.py, tools/, wrangler.toml, .gitignore, README.md,
    google-apps-script.gs, the master photos, Logo.png,
    site/style.css, site/script.js

What it deliberately does NOT copy
    .git            - the new city needs its own repo
    site/*.html     - regenerated by build.py
    site/images/    - regenerated by build.py --images and make-logo.py
    the content markdown - each city needs its own copy, so a clearly
                      labelled skeleton is written instead

Nothing in the source folder is modified.
"""
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_ROOT = os.path.dirname(HERE)


# --------------------------------------------------------------------------
#  Prompting
# --------------------------------------------------------------------------
def ask(label, default=""):
    suffix = " [%s]" % default if default else ""
    while True:
        val = input("  %s%s: " % (label, suffix)).strip()
        if not val and default:
            return default
        if val:
            return val
        print("     (required)")


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def collect():
    print("\nNew city setup")
    print("=" * 60)
    city = ask("City name (e.g. Kitchener)")
    province = ask("Province", "Ontario")
    province_code = ask("Province code", "ON")
    region = ask("Region (e.g. Waterloo Region)")
    business = ask("Business name", "%s Epoxy Floors" % city)
    phone = ask("Phone, display format (e.g. +1 226-555-0100)")
    domain = ask("Live domain", "https://%sepoxyfloors.com" % slugify(city).replace("-", ""))
    area = ask("Service area, comma separated", city)
    lat = ask("Latitude (optional, for schema)", "")
    lng = ask("Longitude (optional, for schema)", "")

    default_dest = os.path.join(os.path.dirname(SRC_ROOT), "%s Epoxy Flooring" % city)
    dest = ask("Create project in", default_dest)

    keep = ask("Reuse the photos from this project? (y/n)", "y").lower().startswith("y")

    return {
        "city": city,
        "province": province,
        "province_code": province_code,
        "region": region,
        "business": business,
        "phone_display": phone,
        "phone_href": "+" + re.sub(r"\D", "", phone),
        "domain": domain.rstrip("/"),
        "service_area": [a.strip() for a in area.split(",") if a.strip()],
        "lat": lat,
        "lng": lng,
        "dest": dest,
        "keep_photos": keep,
        "slug": slugify(business),
    }


# --------------------------------------------------------------------------
#  Copying
# --------------------------------------------------------------------------
ROOT_FILES = [
    "build.py", "wrangler.toml", ".gitignore", "README.md",
    "google-apps-script.gs", "NEXT-BUILD-PROMPT.md", "NEW-CITY.md",
]
SITE_FILES = ["style.css", "script.js"]


def copy_project(cfg):
    dest = cfg["dest"]
    if os.path.exists(dest) and os.listdir(dest):
        sys.exit("Refusing to write into a non-empty folder:\n  %s" % dest)

    os.makedirs(os.path.join(dest, "site", "images"), exist_ok=True)
    os.makedirs(os.path.join(dest, "tools"), exist_ok=True)

    for name in ROOT_FILES:
        src = os.path.join(SRC_ROOT, name)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(dest, name))

    for name in os.listdir(HERE):
        if name.endswith(".py"):
            shutil.copy2(os.path.join(HERE, name), os.path.join(dest, "tools", name))

    for name in SITE_FILES:
        src = os.path.join(SRC_ROOT, "site", name)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(dest, "site", name))

    # Photos and logo master live in the project root
    if cfg["keep_photos"]:
        for name in os.listdir(SRC_ROOT):
            if name.lower().endswith(".png"):
                shutil.copy2(os.path.join(SRC_ROOT, name), os.path.join(dest, name))
        print("  copied master photos and Logo.png")
    else:
        logo = os.path.join(SRC_ROOT, "Logo.png")
        if os.path.exists(logo):
            shutil.copy2(logo, os.path.join(dest, "Logo.png"))
        print("  copied Logo.png only - add this city's photos yourself")

    return dest


# --------------------------------------------------------------------------
#  Rewriting
# --------------------------------------------------------------------------
def rewrite_config(dest, cfg):
    path = os.path.join(dest, "build.py")
    s = open(path, encoding="utf-8").read()

    content_file = "%s-Website-Content.md" % cfg["slug"].title().replace("-", "-")
    area = ",\n    ".join('"%s"' % a for a in cfg["service_area"])
    topbar = ", ".join(cfg["service_area"][:4])
    if cfg["region"]:
        topbar += " &amp; the " + cfg["region"]

    swaps = [
        (r'^BUSINESS      = ".*"$',      'BUSINESS      = "%s"' % cfg["business"]),
        (r'^CITY          = ".*"$',      'CITY          = "%s"' % cfg["city"]),
        (r'^PROVINCE      = ".*"$',      'PROVINCE      = "%s"' % cfg["province"]),
        (r'^PROVINCE_CODE = ".*"$',      'PROVINCE_CODE = "%s"' % cfg["province_code"]),
        (r'^REGION        = ".*"$',      'REGION        = "%s"' % cfg["region"]),
        (r'^PHONE_DISPLAY = ".*"$',      'PHONE_DISPLAY = "%s"' % cfg["phone_display"]),
        (r'^PHONE_HREF    = ".*"$',      'PHONE_HREF    = "%s"' % cfg["phone_href"]),
        (r'^DOMAIN = ".*"$',             'DOMAIN = "%s"' % cfg["domain"]),
        (r'^CONTENT_FILE = ".*"$',       'CONTENT_FILE = "%s"' % content_file),
        (r'^TOPBAR_AREA = ".*"$',        'TOPBAR_AREA = "%s"' % topbar),
        (r'^STREET_ADDRESS = ".*"$',     'STREET_ADDRESS = "PLACEHOLDER - add street address"'),
        (r'^POSTAL_CODE    = ".*"$',     'POSTAL_CODE    = "PLACEHOLDER"'),
    ]
    if cfg["lat"]:
        swaps.append((r'^LATITUDE       = ".*"$', 'LATITUDE       = "%s"' % cfg["lat"]))
    if cfg["lng"]:
        swaps.append((r'^LONGITUDE      = ".*"$', 'LONGITUDE      = "%s"' % cfg["lng"]))

    for pattern, replacement in swaps:
        s, count = re.subn(pattern, replacement, s, count=1, flags=re.M)
        if not count:
            print("  WARNING: could not rewrite %s" % pattern)

    s = re.sub(r"^SERVICE_AREA = \[.*?\]$",
               "SERVICE_AREA = [\n    %s,\n]" % area, s, count=1, flags=re.M | re.S)

    open(path, "w", encoding="utf-8").write(s)
    return content_file


def write_content_skeleton(dest, cfg, content_file):
    """A clearly labelled stub. The real copy is written per city."""
    path = os.path.join(dest, content_file)
    open(path, "w", encoding="utf-8").write(
        "# HOME PAGE\n\n"
        "# Epoxy Flooring In %s\n\n"
        "## PLACEHOLDER - replace this whole file\n\n"
        "This file is a stub. Generate the real copy for %s and paste it here,\n"
        "keeping the exact same structure as the Grimsby content file:\n\n"
        "  - `# HOME PAGE` marker, then the page H1, then `## ` sections\n"
        "  - a `## Frequently Asked Questions` section with `### ` questions\n"
        "  - `---` between pages\n"
        "  - `# SERVICE PAGE 1` through `6`, `# ABOUT PAGE`, `# CONTACT PAGE`,\n"
        "    `# FAQ SECTION`, `# SEO TITLES AND META DESCRIPTIONS`\n\n"
        "The home page must contain one section whose heading starts with\n"
        "\"Why Choose\" and one starting with \"Serving\" - build.py looks those\n"
        "up by prefix.\n\n"
        "See NEW-CITY.md for the content prompt to use.\n"
        % (cfg["city"], cfg["business"]))


def rewrite_side_files(dest, cfg):
    # wrangler.toml - the Worker name must match what you create in Cloudflare
    path = os.path.join(dest, "wrangler.toml")
    if os.path.exists(path):
        s = open(path, encoding="utf-8").read()
        s = re.sub(r'^name = ".*"$', 'name = "%s"' % cfg["slug"], s, count=1, flags=re.M)
        open(path, "w", encoding="utf-8").write(s)

    # web manifest
    path = os.path.join(dest, "site", "site.webmanifest")
    open(path, "w", encoding="utf-8").write(
        '{\n'
        '  "name": "%s",\n'
        '  "short_name": "%s",\n'
        '  "description": "Epoxy flooring, garage floor coating and polyaspartic systems in %s, %s.",\n'
        '  "start_url": "/",\n'
        '  "display": "browser",\n'
        '  "background_color": "#ffffff",\n'
        '  "theme_color": "#0b4d25",\n'
        '  "icons": [\n'
        '    { "src": "images/icon-192.png", "sizes": "192x192", "type": "image/png" },\n'
        '    { "src": "images/icon-512.png", "sizes": "512x512", "type": "image/png" },\n'
        '    { "src": "images/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable" }\n'
        '  ]\n'
        '}\n' % (cfg["business"], cfg["city"] + " Epoxy", cfg["city"], cfg["province"]))

    # script.js - clear the previous city's form endpoint
    path = os.path.join(dest, "site", "script.js")
    if os.path.exists(path):
        s = open(path, encoding="utf-8").read()
        s = re.sub(r"var SHEET_ENDPOINT = '.*?';",
                   "var SHEET_ENDPOINT = 'YOUR-APPS-SCRIPT-WEB-APP-URL';", s, count=1)
        open(path, "w", encoding="utf-8").write(s)


# --------------------------------------------------------------------------
def main():
    cfg = collect()

    print("\nCreating project")
    print("=" * 60)
    dest = copy_project(cfg)
    content_file = rewrite_config(dest, cfg)
    write_content_skeleton(dest, cfg, content_file)
    rewrite_side_files(dest, cfg)

    print("  rewrote CONFIG in build.py")
    print("  wrote content stub: %s" % content_file)
    print("  reset the form endpoint in site/script.js")
    print("  set Worker name to '%s' in wrangler.toml" % cfg["slug"])

    print("\nDone: %s" % dest)
    print("""
Next steps - full detail in NEW-CITY.md
  1. Write the copy into %s
  2. Add or confirm the photos, then check PAGE_PHOTOS / GALLERY_PHOTOS
     in build.py match the filenames
  3. python tools/make-logo.py
  4. python build.py --images
  5. Set up the Google Sheet and paste the endpoint into site/script.js
  6. python build.py
  7. git init, commit, push to a new repo
  8. Cloudflare: import the repo, Worker name must be exactly '%s'
""" % (content_file, cfg["slug"]))


if __name__ == "__main__":
    main()
